#- name: including python setup role from common
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: python_setup


- name: install docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker