- name: disable nginx
  ansible.builtin.shell: dnf module disable nginx -y

- name: enable nginx 24
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: copy nginx conf file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: remove existing app-content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: create application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download and extract app-content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: restart and enable the nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true

#- name: install docker
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: docker
#
#- name: Start App container
#  containers.podman.podman_container:
#    name: frontend
#    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
#    state: started
#    restart: true
#    restart_policy: "always"
#    ports:
#      - "80:80"
#    env:
#      CATALOGUE_HOST: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:CATALOGUE_HOST token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#      CATALOGUE_PORT: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:CATALOGUE_PORT token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#      USER_HOST: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:USER_HOST token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#      USER_PORT: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:USER_PORT token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#      CART_HOST: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:CART_HOST token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#      CART_PORT: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:CART_PORT token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#      SHIPPING_HOST: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:SHIPPING_HOST token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#      SHIPPING_PORT: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:SHIPPING_PORT token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#      PAYMENT_HOST: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:PAYMENT_HOST token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#      PAYMENT_PORT: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/frontend:PAYMENT_PORT token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
#
