#- name: including nodejs set role from common
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: nodejs


- name: install docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Start App container
  containers.podman.podman_container:
    name: cart
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
    state: started
    restart: true
    restart_policy: "always"
    ports:
      - "8080:8080"
    env:
      CATALOGUE_HOST: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/cart:CATALOGUE_HOST token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
      CATALOGUE_PORT: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/cart:CATALOGUE_PORT token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"
      REDIS_HOST: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/cart:REDIS_HOST token={{ vault_token }} url=http://vault-internal.siddevsecops.icu:8200')}}"