#- name: including nodejs set role from common
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: nodejs


- name: install docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker